# Generated by Django 4.1.7 on 2023-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='refund_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
