# Generated by Django 4.1.7 on 2023-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
