# Generated by Django 4.1.7 on 2023-04-03 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0005_alter_userprofile_district_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('products', models.ManyToManyField(to='homeapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
