# Generated by Django 4.1.7 on 2023-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
    ]
