# Generated by Django 4.1.7 on 2023-04-05 04:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur')], max_length=20, null=True),
        ),
    ]
