# Generated by Django 4.1.7 on 2023-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_product_new_slug_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_slug',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
