# Generated by Django 4.1.7 on 2023-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_remove_product_new_slug_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
