# Generated by Django 4.1.7 on 2023-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad')], max_length=20, null=True),
        ),
    ]
